-- ============================================
-- POPULATE COUNTRY/REGION FROM ARTIST_MASTER
-- ============================================

UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'burna boy';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'wizkid';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'davido';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'rema';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'asake';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'tems';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'ckay';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'ayra starr';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'fela kuti';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'kizz daniel';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'omah lay';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'fireboy dml';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'olamide';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'tiwa savage';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'yemi alade';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'ruger';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'p square';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'dbanj';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = '2baba';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE LOWER(matched_artist) = 'black coffee';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE LOWER(matched_artist) = 'tyla';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE LOWER(matched_artist) = 'kabza de small';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE LOWER(matched_artist) = 'dj maphorisa';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE LOWER(matched_artist) = 'master kg';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE LOWER(matched_artist) = 'nasty c';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE LOWER(matched_artist) = 'focalistic';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE LOWER(matched_artist) = 'uncle waffles';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE LOWER(matched_artist) = 'black sherif';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE LOWER(matched_artist) = 'sarkodie';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE LOWER(matched_artist) = 'stonebwoy';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE LOWER(matched_artist) = 'shatta wale';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE LOWER(matched_artist) = 'king promise';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE LOWER(matched_artist) = 'kidi';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE LOWER(matched_artist) = 'kuami eugene';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE LOWER(matched_artist) = 'diamond platnumz';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE LOWER(matched_artist) = 'harmonize';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE LOWER(matched_artist) = 'rayvanny';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE LOWER(matched_artist) = 'zuchu';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE LOWER(matched_artist) = 'ali kiba';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE LOWER(matched_artist) = 'fally ipupa';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE LOWER(matched_artist) = 'koffi olomide';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE LOWER(matched_artist) = 'innossb';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE LOWER(matched_artist) = 'gims';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE LOWER(matched_artist) = 'dadju';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE LOWER(matched_artist) = 'papa wemba';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'saifond balde';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'azaya';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'sekouba bambino';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'mory kante';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'soul bangs';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'djanii alfa';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'instinct killers';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'straiker';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'king alasko';
UPDATE video_intelligence SET country = 'SN', region = 'West Africa' WHERE LOWER(matched_artist) = 'youssou ndour';
UPDATE video_intelligence SET country = 'SN', region = 'West Africa' WHERE LOWER(matched_artist) = 'akon';
UPDATE video_intelligence SET country = 'SN', region = 'West Africa' WHERE LOWER(matched_artist) = 'wally seck';
UPDATE video_intelligence SET country = 'CI', region = 'West Africa' WHERE LOWER(matched_artist) = 'dj arafat';
UPDATE video_intelligence SET country = 'CI', region = 'West Africa' WHERE LOWER(matched_artist) = 'magic system';
UPDATE video_intelligence SET country = 'CI', region = 'West Africa' WHERE LOWER(matched_artist) = 'alpha blondy';
UPDATE video_intelligence SET country = 'KE', region = 'East Africa' WHERE LOWER(matched_artist) = 'sauti sol';
UPDATE video_intelligence SET country = 'KE', region = 'East Africa' WHERE LOWER(matched_artist) = 'nyashinski';
UPDATE video_intelligence SET country = 'ML', region = 'West Africa' WHERE LOWER(matched_artist) = 'salif keita';
UPDATE video_intelligence SET country = 'ML', region = 'West Africa' WHERE LOWER(matched_artist) = 'amadou mariam';
UPDATE video_intelligence SET country = 'ET', region = 'East Africa' WHERE LOWER(matched_artist) = 'teddy afro';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'adekunle gold';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'simi';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'wande coal';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'flavour';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'tekno';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'phyno';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'zlatan';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'mr eazi';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'joeboy';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'bnxn';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'victony';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'pheelz';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'bella shmurda';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'seyi vibez';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'oxlade';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'mayorkun';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'falz';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'patoranking';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'timaya';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE LOWER(matched_artist) = 'young stunna';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE LOWER(matched_artist) = 'dbn gogo';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE LOWER(matched_artist) = 'cassper nyovest';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE LOWER(matched_artist) = 'makhadzi';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE LOWER(matched_artist) = 'a reece';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'takana zion';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'mamady keita';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'koury simple';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'bembeya jazz';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'mc freshh';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'thiird';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'maxim bk';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'wada du game';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'hezbo rap';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE LOWER(matched_artist) = 'nandy';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE LOWER(matched_artist) = 'mbosso';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE LOWER(matched_artist) = 'marioo';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE LOWER(matched_artist) = 'ferre gola';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE LOWER(matched_artist) = 'heritier watanabe';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE LOWER(matched_artist) = 'werrason';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE LOWER(matched_artist) = 'aya nakamura';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE LOWER(matched_artist) = 'damso';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE LOWER(matched_artist) = 'gyakie';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE LOWER(matched_artist) = 'camidoh';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE LOWER(matched_artist) = 'medikal';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE LOWER(matched_artist) = 'kwesi arthur';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE LOWER(matched_artist) = 'r2bees';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'burna boy';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'wizkid';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'wizkid';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'davido';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'fela kuti';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE LOWER(matched_artist) = 'diamond platnumz';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE LOWER(matched_artist) = 'black coffee';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'p square';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'p square';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE LOWER(matched_artist) = 'innossb';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE LOWER(matched_artist) = 'innossb';
UPDATE video_intelligence SET country = 'SN', region = 'West Africa' WHERE LOWER(matched_artist) = 'youssou ndour';
UPDATE video_intelligence SET country = 'SN', region = 'West Africa' WHERE LOWER(matched_artist) = 'youssou ndour';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'sekouba bambino';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE LOWER(matched_artist) = 'sekouba bambino';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE LOWER(matched_artist) = 'gims';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE LOWER(matched_artist) = 'gims';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'bnxn';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE LOWER(matched_artist) = 'bnxn';

-- Fallback: Update from artist column if matched_artist missed
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%burna boy%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%wizkid%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%davido%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%rema%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%asake%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%tems%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%ckay%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%ayra starr%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%fela kuti%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%kizz daniel%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%omah lay%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%fireboy dml%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%olamide%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%tiwa savage%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%yemi alade%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%ruger%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%p square%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%dbanj%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%2baba%';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%black coffee%';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%tyla%';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%kabza de small%';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%dj maphorisa%';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%master kg%';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%nasty c%';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%focalistic%';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%uncle waffles%';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%black sherif%';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%sarkodie%';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%stonebwoy%';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%shatta wale%';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%king promise%';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%kidi%';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%kuami eugene%';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%diamond platnumz%';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%harmonize%';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%rayvanny%';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%zuchu%';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%ali kiba%';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%fally ipupa%';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%koffi olomide%';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%innossb%';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%gims%';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%dadju%';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%papa wemba%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%saifond balde%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%azaya%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%sekouba bambino%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%mory kante%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%soul bangs%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%djanii alfa%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%instinct killers%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%straiker%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%king alasko%';
UPDATE video_intelligence SET country = 'SN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%youssou ndour%';
UPDATE video_intelligence SET country = 'SN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%akon%';
UPDATE video_intelligence SET country = 'SN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%wally seck%';
UPDATE video_intelligence SET country = 'CI', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%dj arafat%';
UPDATE video_intelligence SET country = 'CI', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%magic system%';
UPDATE video_intelligence SET country = 'CI', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%alpha blondy%';
UPDATE video_intelligence SET country = 'KE', region = 'East Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%sauti sol%';
UPDATE video_intelligence SET country = 'KE', region = 'East Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%nyashinski%';
UPDATE video_intelligence SET country = 'ML', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%salif keita%';
UPDATE video_intelligence SET country = 'ML', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%amadou mariam%';
UPDATE video_intelligence SET country = 'ET', region = 'East Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%teddy afro%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%adekunle gold%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%simi%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%wande coal%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%flavour%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%tekno%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%phyno%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%zlatan%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%mr eazi%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%joeboy%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%bnxn%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%victony%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%pheelz%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%bella shmurda%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%seyi vibez%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%oxlade%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%mayorkun%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%falz%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%patoranking%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%timaya%';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%young stunna%';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%dbn gogo%';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%cassper nyovest%';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%makhadzi%';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%a reece%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%takana zion%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%mamady keita%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%koury simple%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%bembeya jazz%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%mc freshh%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%thiird%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%maxim bk%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%wada du game%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%hezbo rap%';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%nandy%';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%mbosso%';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%marioo%';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%ferre gola%';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%heritier watanabe%';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%werrason%';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%aya nakamura%';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%damso%';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%gyakie%';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%camidoh%';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%medikal%';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%kwesi arthur%';
UPDATE video_intelligence SET country = 'GH', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%r2bees%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%burna boy%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%wizkid%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%wizkid%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%davido%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%fela kuti%';
UPDATE video_intelligence SET country = 'TZ', region = 'East Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%diamond platnumz%';
UPDATE video_intelligence SET country = 'ZA', region = 'South Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%black coffee%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%p square%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%p square%';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%innossb%';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%innossb%';
UPDATE video_intelligence SET country = 'SN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%youssou ndour%';
UPDATE video_intelligence SET country = 'SN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%youssou ndour%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%sekouba bambino%';
UPDATE video_intelligence SET country = 'GN', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%sekouba bambino%';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%gims%';
UPDATE video_intelligence SET country = 'CD', region = 'Central Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%gims%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%bnxn%';
UPDATE video_intelligence SET country = 'NG', region = 'West Africa' WHERE country IS NULL AND LOWER(artist) LIKE '%bnxn%';
